/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'solution' : IDL.Text,
});
export const Tutorial = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'difficulty' : IDL.Text,
});
export const UserProgress = IDL.Record({
  'completedTutorials' : IDL.Vec(IDL.Nat),
  'solvedExercises' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  'completeTutorial' : IDL.Func([IDL.Nat], [], []),
  'getExercises' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getTutorials' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Tutorial)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
  'solveExercise' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'solution' : IDL.Text,
  });
  const Tutorial = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'difficulty' : IDL.Text,
  });
  const UserProgress = IDL.Record({
    'completedTutorials' : IDL.Vec(IDL.Nat),
    'solvedExercises' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    'completeTutorial' : IDL.Func([IDL.Nat], [], []),
    'getExercises' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getTutorials' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Tutorial)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
    'solveExercise' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };